=== standen/notes/backend_django/api/json_schemes/system/SystemMenuItems.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "I System Menu Items",
  "type": "object",
  "properties": {
    "accounts": {
      "$ref": "./SystemMenuItem.schema.json"
    },
    "notes": {
      "$ref": "./SystemMenuItem.schema.json"
    },
    "events": {
      "$ref": "./SystemMenuItem.schema.json"
    },
    "pays": {
      "$ref": "./SystemMenuItem.schema.json"
    },
    "settings": {
      "$ref": "./SystemMenuItem.schema.json"
    }
  },
  "required": [
    "accounts",
    "notes",
    "events",
    "pays",
    "settings"
  ],
  "additionalProperties": false
}

=== standen/notes/backend_django/api/json_schemes/system/SystemMenu.json
{
  "accounts": {
    "title": "Аккаунты",
    "url": "/",
    "is_menu_item": true,
    "permissions": []
  },
  "notes": {
    "title": "Заметки",
    "url": "/notes",
    "is_menu_item": true,
    "permissions": []
  },
  "events": {
    "title": "События",
    "url": "/events",
    "is_menu_item": true,
    "permissions": []
  },
  "pays": {
    "title": "Платежи",
    "url": "/pays",
    "is_menu_item": true,
    "permissions": []
  },
  "settings": {
    "title": "Настройки",
    "url": "/settings",
    "is_menu_item": true,
    "permissions": [
      "SETTINGS_SHOW_IN_MENU"
    ]
  }
}

=== standen/notes/backend_django/api/json_schemes/system/SystemPermissions.json
{
  "accounts": {
    "show_in_menu": [
      "ACCOUNTS_SHOW_IN_MENU"
    ],
    "read": [
      "ACCOUNTS_READ"
    ],
    "create": [
      "ACCOUNTS_CREATE"
    ],
    "edit": [
      "ACCOUNTS_EDIT"
    ],
    "delete": [
      "ACCOUNTS_DELETE"
    ]
  },
  "notes": {
    "show_in_menu": [
      "NOTES_SHOW_IN_MENU"
    ],
    "read": [
      "NOTES_READ"
    ],
    "create": [
      "NOTES_CREATE"
    ],
    "edit": [
      "NOTES_EDIT"
    ],
    "delete": [
      "NOTES_DELETE"
    ]
  },
  "events": {
    "show_in_menu": [
      "EVENTS_SHOW_IN_MENU"
    ],
    "read": [
      "EVENTS_READ"
    ],
    "create": [
      "EVENTS_CREATE"
    ],
    "edit": [
      "EVENTS_EDIT"
    ],
    "delete": [
      "EVENTS_DELETE"
    ]
  },
  "pays": {
    "show_in_menu": [
      "PAYS_SHOW_IN_MENU"
    ],
    "read": [
      "PAYS_READ"
    ],
    "create": [
      "PAYS_CREATE"
    ],
    "edit": [
      "PAYS_EDIT"
    ],
    "delete": [
      "PAYS_DELETE"
    ]
  },
  "settings": {
    "show_in_menu": [
      "SETTINGS_SHOW_IN_MENU"
    ],
    "roles": {
      "show_in_tabs": [
        "SETTINGS_ROLES_SHOW_IN_TABS"
      ],
      "read": [
        "SETTINGS_ROLES_READ"
      ],
      "create": [
        "SETTINGS_ROLES_CREATE"
      ],
      "edit": [
        "SETTINGS_ROLES_EDIT"
      ],
      "delete": [
        "SETTINGS_ROLES_DELETE"
      ]
    },
    "users": {
      "show_in_tabs": [
        "SETTINGS_USERS_SHOW_IN_TABS"
      ],
      "read": [
        "SETTINGS_USERS_READ"
      ],
      "create": [
        "SETTINGS_USERS_CREATE"
      ],
      "edit": [
        "SETTINGS_USERS_EDIT"
      ],
      "delete": [
        "SETTINGS_USERS_DELETE"
      ]
    },
    "pays": {
      "show_in_tabs": [
        "SETTINGS_PAYS_SHOW_IN_TABS"
      ],
      "category": {
        "read": [
          "SETTINGS_PAYS_CATEGORY_READ"
        ],
        "create": [
          "SETTINGS_PAYS_CATEGORY_CREATE"
        ],
        "edit": [
          "SETTINGS_PAYS_CATEGORY_EDIT"
        ],
        "delete": [
          "SETTINGS_PAYS_CATEGORY_DELETE"
        ]
      }
    }
  }
}
